import { forwardRef, useEffect, useState } from "react";
import { useLanguage } from "@/hooks/useLanguage";
import { format } from "date-fns";

const LetterPreview = forwardRef(({ template, formData, className = "" }, ref) => {
  const { t, currentLanguage } = useLanguage();
  const [processedContent, setProcessedContent] = useState("");

  useEffect(() => {
    if (template && formData) {
      let content = template.content;
      
      // Replace placeholders with form data
      Object.keys(formData).forEach(key => {
        const placeholder = `{{${key}}}`;
        const value = formData[key] || `[${key}]`;
        content = content.replace(new RegExp(placeholder, 'g'), value);
      });

      setProcessedContent(content);
    }
  }, [template, formData]);

  if (!template) {
    return (
      <div className={`letter-preview ${className}`}>
        <div className="text-center text-gray-500 mt-20">
          {t("ٹیمپلیٹ منتخب کریں", "Select a template")}
        </div>
      </div>
    );
  }

  return (
    <div ref={ref} className={`letter-preview ${className} ${currentLanguage === "urdu" ? "urdu-text rtl" : "english-text ltr"}`}>
      <div className="text-center mb-8">
        <h1 className="text-2xl font-bold text-primary border-b-2 border-primary pb-3 mb-4">
          {currentLanguage === "urdu" ? template.titleUrdu : template.titleEnglish}
        </h1>
        <p className="text-sm text-gray-600">
          {t("تاریخ", "Date")}: {format(new Date(), "dd/MM/yyyy")}
        </p>
      </div>

      <div className="text-justify leading-relaxed">
        <div className="whitespace-pre-wrap">
          {processedContent}
        </div>
      </div>

      <div className="mt-16 pt-8 border-t border-gray-300">
        <div className="flex justify-between items-end">
          <div>
            <p className="text-sm text-gray-600 mb-2">
              {t("درخواست گزار کا دستخط", "Applicant's Signature")}
            </p>
            <div className="w-40 h-12 border-b border-gray-400"></div>
          </div>
          <div className="text-right">
            <p className="text-sm text-gray-600 mb-2">
              {t("تاریخ", "Date")}
            </p>
            <div className="w-32 h-12 border-b border-gray-400"></div>
          </div>
        </div>
      </div>

      <div className="mt-8 text-center text-xs text-gray-500">
        <p>Generated by شکوہ نویس (Shikawa Nawees)</p>
      </div>
    </div>
  );
});

LetterPreview.displayName = "LetterPreview";

export default LetterPreview;